[build]
  command = "npm run build && cp _headers build/_headers && mv build/404/index.html build/404.html && rm -r build/404"
  publish = "build"
 
[dev]
 command = "svelte-kit dev"
 
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"